NDefines.NGame.RNW_MERC_COMPANY_ARTILLERY_MAX = 0.5
NDefines.NDiplomacy.ESTATE_DISLIKE_ALLIANCE_ON_VC = 0.0

NDefines.NMilitary.STRELTSY_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.STRELTSY_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.STRELTSY_STARTING_MORALE = 1